



services:
  angular:
    build: ./meu-projeto-frontend
    container_name: container_angular-2
    restart: always
    # expose:
      
    volumes:
      - html_angular:/output


    networks:
      - rede_compartilhada

      
volumes:
  html_angular:
    external: true

networks:
  rede_compartilhada:
    external: true













# services:
#   angular:
#     build: ./meu-projeto-frontend
#     container_name: container_angular-2
#     restart: always
#     networks:
#       - rede_compartilhada

# networks:
#   rede_compartilhada:
#     external: true






