 server {
    listen 80;
    
     location / {
         root /usr/share/nginx/html;
         index index.html index.htm;
         # Esta linha resolve o erro 404 de rotas do Angular:
         try_files $uri $uri/ /index.html;
 }
 }